"use client"

import {Poppins} from "next/font/google";
import React, {useEffect, useReducer} from "react";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "./components/Footer";
import Header from "./components/Header";
import {ProductContext} from './context/cartContext';
import "./globals.css";
import {cartReducer, initialState} from './reducer/CartReducer';
import {SearchProvider} from "./reducer/SearchContext";

const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '800'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
});

// export const metadata = {
//   title: "Abaya Shop",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}) {
    const [state, dispatch] = useReducer(cartReducer, initialState);
    useEffect(() => {
        dispatch({
            type: 'SET_CART'
        });
    }, [])


    return (
        <html lang="en">
        <body className={poppins.className}>
        <ProductContext.Provider value={{state, dispatch}}>
            <SearchProvider>
                <Header/>
                {children}
                <Footer/>
                <ToastContainer/>
            </SearchProvider>
        </ProductContext.Provider>
        </body>
        </html>
    );
}
